version: "3.8"

services:
  postgres:
    image: postgres:17.5
    container_name: postgres-db
    restart: always
    ports:
      - "5422:5432"
    environment:
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
      POSTGRES_DB: petclinic
    volumes:
      - ./pgdata:/var/lib/postgresql/data